---
title: "Scaling_and_Clustering_Fusions"
author: "Brian Haas"
date: "2/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(umap)
suppressPackageStartupMessages(library(leiden))
library(cowplot)
library(ggrepel)
library(FNN)
library(igraph)
library(pheatmap)
```

```{r}

FRACTION_DATA_USE = 0.20 # set to 1.0 to use all data

fusion_data = read.table(gzfile("../data/FusionInspector.v2.4.0.TARGET.tsv.gz"), header=T, sep="\t", stringsAsFactors = F)

# strip out earlier computed values when using here.
fusion_data = fusion_data[, ! grepl("^adj", colnames(fusion_data))]
fusion_data = fusion_data[, ! (colnames(fusion_data) %in% c('is_primary', 'cosmic', 'leiden', 'umap1', 'umap2'))]

```


```{r}

# resurrect attributes as defined below:

# set primary fusion variant
fusion_data = fusion_data %>% group_by(sample, fusion_name) %>% arrange(desc(FFPM)) %>% mutate(is_primary = (row_number()==1)) %>% ungroup()


# set known cosmic attribute

cosmic_fusions = read.table("../data/cosmic.list", header=F, stringsAsFactors = F)[,1]

fusion_data = fusion_data %>% mutate(cosmic = (fusion_name %in% cosmic_fusions))


```


```{r}

fusion_data = fusion_data %>% sample_frac(FRACTION_DATA_USE)


```




```{r}
# prep data for scaling and clustering

pseudocount = 1
data = data.frame(adj_annot_splice=fusion_data$annot_splice, 
                  adj_consensus_splice=fusion_data$consensus_splice)

data$adj_FFPM=log2(fusion_data$FFPM+pseudocount)
data$adj_left_counter_ffpm = log2(fusion_data$left_counter_ffpm+pseudocount)
data$adj_right_counter_ffpm = log2(fusion_data$right_counter_ffpm+pseudocount)
data$adj_FAR_left = log2(fusion_data$FAR_left+pseudocount)
data$adj_FAR_right = log2(fusion_data$FAR_right+pseudocount)
data$adj_microh_brkpt_dist = log2(fusion_data$microh_brkpt_dist+1)
data$adj_num_microh = log2(fusion_data$num_microh_near_brkpt+1)

```

```{r}
data %>% gather(key=key, value=value, 
                adj_annot_splice, adj_consensus_splice,
                adj_FFPM, adj_left_counter_ffpm, adj_right_counter_ffpm, 
                adj_FAR_left, adj_FAR_right, adj_microh_brkpt_dist, adj_num_microh) %>% ggplot(aes(x=key, y=value)) + geom_violin() +  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
data.colmeans = colMeans(data)
message("data.colmeans")
data.colmeans

data.sd = apply(data, 2, sd)
message("data.sd")
data.sd


```


```{r}
data.scaled = scale(data, center=T, scale=T)
data.scaled.df = as.data.frame(data.scaled)
data.scaled.df %>% gather() %>% ggplot(aes(x=key, y=value)) + geom_violin() +  
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



```{r}
# truncate to interval [-2,2]
data.scaled[data.scaled < -2] = -2
data.scaled[data.scaled > 2] = 2

data.scaled.df = as.data.frame(data.scaled)

as.data.frame(data.scaled) %>% gather() %>% ggplot(aes(x=key, y=value)) + geom_violin() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

Do another round of scaling to the -2,2 interval:


```{r}

apply(data.scaled, 2, range)

```


```{r}

rescale = function(vals, scale_range=c(-2,2)) {
  
  min_val = min(vals)
  max_val = max(vals)
  
  inrange = max_val - min_val
  outrange = scale_range[2] - scale_range[1]
  
  adj_vals = (vals - min_val) / inrange * outrange + scale_range[1]
  
  return(adj_vals)
}

data.scaled = apply(data.scaled, 2, rescale)

data.scaled.df = as.data.frame(data.scaled)

as.data.frame(data.scaled) %>% gather() %>% ggplot(aes(x=key, y=value)) + geom_violin() +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



## umap on data.scaled

```{r}

umap.mydefaults = umap.defaults
umap.mydefaults$random_state =  123456
data.scaled.umap = umap(data.scaled, config=umap.mydefaults)
saveRDS(data.scaled.umap, file="data.scaled.umap.rds")
umap.data = data.scaled.umap$layout
colnames(umap.data) = c('umap1', 'umap2')
```


```{r}


as.data.frame(umap.data) %>% ggplot(aes(x = umap1, y = umap2)) + 
    geom_point(alpha = 0.3, size=0.1) + theme_bw() + ggtitle("umap data.scaled") 

```






```{r}
# merge all back to the fusion_data table

fusion_data = cbind(fusion_data, data.scaled)
fusion_data = cbind(fusion_data, umap.data)




```



```{r}

## Clustering Fusions 

# note, this step can take a while

LEIDEN_RESOLUTION = 2.0

k = 50
knn = get.knn(data.scaled, k = k)

knn.dist = data.frame(
    from = rep(1:nrow(knn$nn.index), k), 
    to = as.vector(knn$nn.index), 
    weight = 1/(1 + as.vector(knn$nn.dist)))

knn.graph = graph_from_data_frame(knn.dist, directed = FALSE)
knn.graph.simple = simplify(knn.graph)


adjacency_matrix <- igraph::as_adjacency_matrix(knn.graph.simple)
partition <- leiden(adjacency_matrix, seed=12345, resolution_parameter = LEIDEN_RESOLUTION)
table(partition)


```


```{r}

save.image(paste0("saved.", FRACTION_DATA_USE, ".pre.RData"))

```

```{r}


fusion_data$leiden = as.character(partition)

```


```{r}
umap.layout.cent = fusion_data %>% select(umap1, umap2, leiden) %>% group_by(leiden) %>% summarize_all(mean)


plot_umap = function() {

    p = fusion_data %>% ggplot(aes(x = umap1, y = umap2, colour = leiden)) + 
        geom_point(alpha = 0.3) + 
        theme_bw() + 
        geom_label_repel(data=umap.layout.cent, aes(label = leiden)) + 
                             guides(colour = FALSE)

    return(p)
}

umap_plot = plot_umap()

# highlight the cosmic entries

cosmic_subset = fusion_data %>% filter(cosmic == TRUE)

p = umap_plot + geom_point(data=cosmic_subset, color='black')

plot(p)


```

## restrict cosmic entries to just those highest expressed isoforms per sample.

```{r}
cosmic.primary_isoform = cosmic_subset %>% filter(is_primary)

p = umap_plot + geom_point(data=cosmic.primary_isoform, color='black')

plot(p)

```



Cosmic fusion cluster content
```{r}

max_cluster = max(partition)

all_median_vals_df = NULL



for (cluster_i in seq(max_cluster)) {

    #message("cluster: ", cluster_i)
    
    cluster_row_indices = which(fusion_data$leiden == cluster_i)
    
    feature_atts = data.scaled[cluster_row_indices,]
    
    median_vals = as_tibble(feature_atts) %>% gather() %>% group_by(key) %>% summarize(m=median(value))

    df = data.frame(median_vals$m, row.names=median_vals$key)
    df = as.data.frame(t(df))
    df$cluster = cluster_i

    all_median_vals_df = bind_rows(all_median_vals_df, df)

}


rownames(all_median_vals_df) = all_median_vals_df$cluster

all_median_vals_df = all_median_vals_df[,!c(colnames(all_median_vals_df)=='cluster')]

```

```{r}

median_vals_pca = prcomp(t(all_median_vals_df))
rows_d = dist(median_vals_pca$rotation[,1:6])
rowclust = hclust(as.dist(rows_d), "ward.D")


cols_d = dist(t(all_median_vals_df))

colclust = hclust(as.dist(cols_d), "ward.D")



p = pheatmap(all_median_vals_df, 
             cluster_rows=rowclust,
             cluster_cols=colclust,
             )

```


plot cosmic primary isoform fusion counts according to cluster

```{r}


cosmic_counts_per_cluster = cosmic.primary_isoform %>%
    group_by(fusion_name, leiden) %>% 
    tally()

cosmic_counts_per_cluster$leiden = factor(cosmic_counts_per_cluster$leiden, levels=rev(p$tree_row$labels[p$tree_row$order]))

empty_counts_df = data.frame(fusion_name="NA", leiden=factor(seq(max_cluster), levels=rev(p$tree_row$labels[p$tree_row$order])), n=0)

cosmic_counts_per_cluster = bind_rows(empty_counts_df, cosmic_counts_per_cluster)



# plot it

cosmic_sum_counts_per_cluster = cosmic_counts_per_cluster %>% group_by(leiden) %>% summarize(sum_n = sum(n))
cosmic_all_iso_counts_per_cluster_plot = cosmic_counts_per_cluster %>% ggplot(aes(x=leiden, y=n, fill=fusion_name)) + geom_col() + coord_flip() + ggtitle("COSMIC primary isoform count")



plot(cosmic_all_iso_counts_per_cluster_plot)
```


```{r}

# all fusions, top isoforms


top_fusion_counts_per_cluster = fusion_data %>% 
    filter(is_primary) %>%
    select(fusion_name, leiden) %>% 
    group_by(fusion_name, leiden) %>% 
    tally()

top_fusion_counts_per_cluster$leiden = factor(top_fusion_counts_per_cluster$leiden, levels=rev(p$tree_row$labels[p$tree_row$order]))

empty_counts_df = data.frame(fusion_name="NA", leiden=factor(seq(max_cluster), levels=rev(p$tree_row$labels[p$tree_row$order])), n=0)


top_fusion_counts_per_cluster = bind_rows(empty_counts_df, top_fusion_counts_per_cluster)

sum_fusion_counts_per_cluster = top_fusion_counts_per_cluster %>% group_by(leiden) %>% summarize(sum_n = sum(n))

sum_fusion_counts_per_cluster_plot = sum_fusion_counts_per_cluster %>% ggplot(aes(x=leiden, y=sum_n)) + geom_col() + coord_flip() + ggtitle("Fusion primary isoform count")

plot(sum_fusion_counts_per_cluster_plot)
```

plot cosmic enrichment per cluster

```{r}

cosmic_sum_counts_per_cluster$fusion_type = "cosmic"
sum_fusion_counts_per_cluster$fusion_type = "all"
cosmic_and_all_counts_df = bind_rows(cosmic_sum_counts_per_cluster, sum_fusion_counts_per_cluster)

cosmic_and_all_counts_df = cosmic_and_all_counts_df %>% spread(key=fusion_type, value=sum_n)
cosmic_and_all_counts_df = cosmic_and_all_counts_df %>% mutate(frac_cosmic = cosmic/all)

cosmic_frac_enrichment_plot = cosmic_and_all_counts_df %>% ggplot(aes(x=leiden, y=frac_cosmic)) + 
    geom_col() + coord_flip() + ggtitle("Fraction COSMIC fusions")
plot(cosmic_frac_enrichment_plot)
```



Create single summary plot

```{r}


cosmic_all_iso_counts_per_cluster_plot_NLeg = cosmic_all_iso_counts_per_cluster_plot + 
    theme(legend.position = "none")

pg = plot_grid(p[[4]], cosmic_all_iso_counts_per_cluster_plot_NLeg, sum_fusion_counts_per_cluster_plot, cosmic_frac_enrichment_plot, 
          nrow=1, rel_widths = c(3,1,1,1) )

plot(pg)

```



```{r}

save.image(paste0("saved.", FRACTION_DATA_USE, ".final.RData"))

```



