---
title: "Cluster_assignment_variation_among_matched_samples.Rmd"
author: "bhaas"
date: '2022-08-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pheatmap)
library(cowplot)
library(igraph)
```


```{r}
data = read.table(gzfile("../../data/FusionInspector.v2.4.0.examine_recurrents.tsv.gz"), header=T, com='', sep="\t", stringsAsFactors = F)

data = data %>% mutate(fusion_variant = paste(fusion_name, LeftBreakpoint, RightBreakpoint))

```

# examine TCGA
```{r}

tcga_data = data %>% filter(data_class == "TCGA")

tcga_data$type = sapply(tcga_data$sample_name, function(x) {str_split(x, "-")[[1]][4] })

tcga_data$participant = sapply(tcga_data$sample_name, function(x) { vals = str_split(x, "-")[[1]]; paste(vals[c(1,2,3)], collapse ="-") })

```

```{r}
# get those fusions that are in matched samples
tcga_samples_with_matched_fusions = tcga_data %>%  group_by(participant, fusion_variant) %>% tally() %>% filter(n>1)

tcga_data_matched_fusions = left_join(tcga_samples_with_matched_fusions %>% select(participant, fusion_variant),
                                      tcga_data,
                                      by=c('participant', 'fusion_variant'))





```



```{r}

tcga_data_matched_fusions %>% select(participant, fusion_variant, type, leiden, fusion_cluster_att)


```




# Examine GTEx 

```{r}

gtex_data = data %>% filter(data_class == "GTEx")

gtex_data$participant = sapply(gtex_data$sample_name, function(x) { vals = str_split(x, "-")[[1]]; paste(vals[c(1,2)], collapse ="-") })

```

```{r}

gtex_samples_with_matched_fusions = gtex_data %>% group_by(participant, fusion_variant) %>% tally() %>% filter(n>1)

gtex_data_matched_fusions = left_join(gtex_samples_with_matched_fusions %>% select(participant, fusion_variant),
                                      gtex_data,
                                      by=c('participant', 'fusion_variant'))


```



```{r}


gtex_data_matched_fusions %>% select(participant, sample_name, fusion_variant, leiden, fusion_cluster_att)

```


# combine GTEx and TCGA participant-matched diff smaple fusion variants

```{r}

data_matched_fusions = bind_rows(tcga_data_matched_fusions, gtex_data_matched_fusions)


```




```{r}

combined_results = full_join(data_matched_fusions %>% select(participant, sample_name, fusion_variant, leiden, fusion_cluster_att),
                             data_matched_fusions %>% select(participant, sample_name, fusion_variant, leiden, fusion_cluster_att),
                             by = c('participant', 'fusion_variant') ) %>%
  filter(sample_name.x != sample_name.y)

combined_results

```

```{r}

combined_results %>% group_by(leiden.x, leiden.y) %>% tally() 


```


```{r}

combined_results %>% 
  group_by(leiden.x, leiden.y) %>% 
  tally() %>% 
  ggplot(aes(x=factor(leiden.x), y=n, fill=factor(leiden.y))) + geom_col() +
  ggtitle("Cluster assignment for matched participant sample fusions")


```

```{r}

# examine matched sample fusions according to the high-level categories
combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>% tally() 



```


```{r}

combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>% tally() %>%
  ggplot(aes(x=fusion_cluster_att.x, y=n, fill=fusion_cluster_att.y)) + geom_col() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  ggtitle("High-level category assignment for matched participant diff sample fusions")


```


```{r}

# examine fractional representation of the above
combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>%  tally() %>%
  group_by(fusion_cluster_att.x) %>% mutate(pct=prop.table(n))  %>%
  ggplot(aes(x=fusion_cluster_att.x, y=pct, fill=fusion_cluster_att.y)) + geom_col() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("High-level category assignment for matched participant diff sample fusions")

```


```{r}


consistency_stats = combined_results %>% select(leiden.x, leiden.y) %>% group_by(leiden.x, leiden.y) %>% tally() %>%
  group_by(leiden.x) %>% mutate(pct=prop.table(n)) %>% mutate(ident_cluster = (leiden.x==leiden.y))

consistency_stats %>% ggplot(aes(x=leiden.x, y=pct, color=ident_cluster)) + geom_col() + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(1) )) + 
  ggtitle("Cluster assignment for participant matched diff sample fusion pairs")

```

```{r}

library(igraph)

graph_weights = consistency_stats %>%  select(i=leiden.x, j=leiden.y, weight=pct)  %>% 
  filter(weight > 0.01) %>% unique()

prediction_accuracy_graph = graph_from_data_frame(graph_weights, directed=FALSE)


g.simplified = simplify(prediction_accuracy_graph)
g.louvain = cluster_louvain(prediction_accuracy_graph, resolution=1)

plot(g.louvain, 
     g.simplified, 
     vertex.size=3, edge.arrow.size = .2)


```


```{r}

load("../3.2.EvaluateClusterPredictionAccuracy/share_data.Rdata")

for (i in 1:length(g.louvain)) {
    clustered_ids = g.louvain[[i]]
    if (length(clustered_ids) > 1) {
        plot_heatmap_n_fusion_counts(clustered_ids)
    }
}

```








