---
title: "examine_biorep_cluster_pred_consistency"
author: "bhaas"
date: '2022-08-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pheatmap)
library(cowplot)
```


```{r}

data = read.table(gzfile("../../data/FusionInspector.v2.4.0.TCGA_bioreps.tsv.gz"), header=T, sep="\t", stringsAsFactors = F, com='') %>%
  rename(sample = X.sample, fusion_name = X.FusionName)


```

```{r}

data = data %>% mutate(fusion_variant = paste(fusion_name, LeftBreakpoint, RightBreakpoint))

```


```{r}


data$participant = sapply(data$sample, function(x) { vals = str_split(x, "-")[[1]]; paste(vals[c(1,2,3)], collapse ="-") })

```



```{r}

repro_fusions = data %>% group_by(participant, fusion_variant) %>% tally() %>% filter(n>2)

repro_fusions_data = left_join(repro_fusions %>% select(-n),
                               data,
                               by=c('participant', 'fusion_variant'))

```



```{r}

#  check reproducibility for cluster-level predictions

repro_fusions_data %>% group_by(participant, fusion_variant, pred_cluster) %>% 
  tally() %>% mutate(agree = (n>1)) %>%
  ggplot(aes(x=factor(pred_cluster), y=n, fill=agree)) + geom_col() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(1) ))


```



```{r}

#  check reproducibility for cluster-level predictions

repro_fusions_data %>% group_by(participant, fusion_variant, pred_cluster) %>% tally() %>% mutate(agree = (n>1)) %>%
  group_by(pred_cluster, agree) %>% summarize(sum_agree = sum(n)) %>%
   mutate(pct=prop.table(sum_agree))  %>%
  ggplot(aes(x=factor(pred_cluster), y=pct, fill=agree)) + geom_col() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(1) ))


```


```{r}

#  check reproducibility for cluster annotation-level predictions

repro_fusions_data %>% mutate(fusion_cluster_att = ifelse(grepl("artifact", fusion_cluster_att), "artifact", fusion_cluster_att) ) %>%
group_by(participant, fusion_variant, fusion_cluster_att) %>% tally() %>% mutate(agree = (n>1)) %>%
  ggplot(aes(x=fusion_cluster_att, y=n, fill=agree)) + geom_col()



repro_fusions_data %>% mutate(fusion_cluster_att = ifelse(grepl("artifact", fusion_cluster_att), "artifact", fusion_cluster_att) ) %>%
group_by(participant, fusion_variant, fusion_cluster_att) %>% tally() %>% mutate(agree = (n>1)) %>%
  group_by(fusion_cluster_att, agree) %>% summarize(sum_agree = sum(n)) %>%
   mutate(pct=prop.table(sum_agree))  %>%
  ggplot(aes(x=fusion_cluster_att, y=pct, fill=agree)) + geom_col()


```



```{r}

library(igraph)


combined_results = full_join(repro_fusions_data %>% select(participant, sample, fusion_variant, pred_cluster, fusion_cluster_att),
                             repro_fusions_data %>% select(participant, sample, fusion_variant, pred_cluster, fusion_cluster_att),
                             by = c('participant', 'fusion_variant') ) %>%
  filter(sample.x != sample.y)


combined_results %>% group_by(pred_cluster.x, pred_cluster.y) %>% tally() 


```


```{r}

combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>% tally() %>%
  ggplot(aes(x=fusion_cluster_att.x, y=n, fill=fusion_cluster_att.y)) + geom_col() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  ggtitle("High-level category assignment for matched participant diff sample fusions")


```



```{r}

# examine fractional representation of the above
combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>%  tally() %>%
  group_by(fusion_cluster_att.x) %>% mutate(pct=prop.table(n))  %>%
  ggplot(aes(x=fusion_cluster_att.x, y=pct, fill=fusion_cluster_att.y)) + geom_col() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("High-level category assignment for matched participant diff sample fusions")

```


```{r}


consistency_stats = combined_results %>% select(pred_cluster.x, pred_cluster.y) %>% group_by(pred_cluster.x, pred_cluster.y) %>% tally() %>%
  group_by(pred_cluster.x) %>% mutate(pct=prop.table(n)) %>% mutate(ident_cluster = (pred_cluster.x==pred_cluster.y))

consistency_stats %>% ggplot(aes(x=factor(pred_cluster.x), y=pct, color=ident_cluster)) + geom_col() + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(1) )) + 
  ggtitle("Cluster assignment for participant matched diff sample fusion pairs")

```




```{r}


graph_weights = consistency_stats %>%  select(i=pred_cluster.x, j=pred_cluster.y, weight=pct)  %>% 
  filter(weight > 0.01) %>% unique()

prediction_accuracy_graph = graph_from_data_frame(graph_weights, directed=FALSE)


g.simplified = simplify(prediction_accuracy_graph)
g.louvain = cluster_louvain(prediction_accuracy_graph, resolution=1)

plot(g.louvain, 
     g.simplified, 
     vertex.size=3, edge.arrow.size = .2)


```


```{r}

load("~/GITHUB/CTAT_FUSIONS/FusionInspectorPaper/3.Annotate_Leiden_Fusion_Clusters/3.2.EvaluateClusterPredictionAccuracy/share_data.Rdata")

for (i in 1:length(g.louvain)) {
    clustered_ids = g.louvain[[i]]
    if (length(clustered_ids) > 1) {
        plot_heatmap_n_fusion_counts(clustered_ids)
    }
}

```








