---
title: "FusionCounting"
author: "Brian Haas"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```



```{r}

data = read.table(gzfile("../data/TCGA_n_GTEx.STAR-Fusion.v1.7.fusion_preds.decorated.tsv.gz"), header=T, sep="\t", stringsAsFactors = F)

data = data %>% mutate(dataclassTN = paste0(data_class, "-", tumor_or_normal))


## some initial cleanup
data = data %>% 
  filter(! grepl("chrM", Annots)) %>%
  filter(! grepl("HLA", fusion_name)) %>%
  filter(! (grepl("^IG[HKVL]", LeftGene) & grepl("^IG[HKVL]", RightGene)))

#Count numbers of samples post basic filtering

data %>% select(dataclassTN, sample) %>% unique() %>% ungroup() %>% group_by(dataclassTN) %>% tally()


```

# tcga stats

```{r}

# number or tcga fusion isoforms called

data %>% filter(data_class == "TCGA") %>% nrow()

# 372681
```


```{r}

# number of TCGA fusions called in > 2 samples

data %>% filter(data_class == "TCGA") %>% select(sample, fusion_name) %>% unique() %>% group_by(fusion_name) %>% tally() %>% filter(n>2) %>% nrow()


# 6134
```

# gtex stats

```{r}

# number or gtex fusion isoforms called

data %>% filter(data_class == "GTEx") %>% nrow()

# 301460

```



```{r}

# number of gtex fusions called in > 2 samples

data %>% filter(data_class == "GTEx") %>% select(sample, fusion_name) %>% unique() %>% group_by(fusion_name) %>% tally() %>% filter(n>2) %>% nrow()

# 4455
```

# Now do the same for FI

```{r}

FI_data = read.table(gzfile("../data/FusionInspector.v2.4.0.examine_recurrents.tsv.gz"), sep="\t", header=T, stringsAsFactors = F)
```


```{r}

#Count numbers of samples post basic filtering

FI_data %>% select(data_class, sample) %>% unique() %>% ungroup() %>% group_by(data_class) %>% tally()

#GTEx	530			
#TCGA	628	
```


```{r}

# number or tcga fusion isoforms called

FI_data %>% filter(data_class == "TCGA") %>% nrow()
# [1] 27880

# number of TCGA fusions called in > 2 samples

FI_data %>% filter(data_class == "TCGA") %>% select(sample, fusion_name) %>% unique() %>% group_by(fusion_name) %>% tally() %>% filter(n>2) %>% nrow()

# [1] 650
```


```{r}

# number or gtex fusion isoforms called

FI_data %>% filter(data_class == "GTEx") %>% nrow()

# [1] 25360


# number of gtex fusions called in > 2 samples

FI_data %>% filter(data_class == "GTEx") %>% select(sample, fusion_name) %>% unique() %>% group_by(fusion_name) %>% tally() %>% filter(n>2) %>% nrow()

#[1] 654

```




