---
title: "Cluster_assignment_variation_among_matched_samples.Rmd"
author: "bhaas"
date: '2022-08-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pheatmap)
library(cowplot)
library(igraph)
```


```{r}
data = read.table(gzfile("../../data/FusionInspector.v2.4.0.C4_targeted_fusions.tsv.gz"), header=T, com='', sep="\t", stringsAsFactors = F)

data = data %>% mutate(fusion_variant = paste(fusion_name, LeftBreakpoint, RightBreakpoint))


```

# examine TCGA
```{r}

tcga_data = data %>% filter(data_class == "TCGA")

tcga_data$type = sapply(tcga_data$sample, function(x) {str_split(x, "-")[[1]][4] })

tcga_data$participant = sapply(tcga_data$sample, function(x) { vals = str_split(x, "-")[[1]]; paste(vals[c(1,2,3)], collapse ="-") })

```

```{r}
# get those fusions that are in matched samples
tcga_samples_with_matched_fusions = tcga_data %>%  group_by(participant, fusion_variant) %>% tally() %>% filter(n>1)

tcga_data_matched_fusions = left_join(tcga_samples_with_matched_fusions %>% select(participant, fusion_variant),
                                      tcga_data,
                                      by=c('participant', 'fusion_variant'))





```



```{r}

tcga_data_matched_fusions %>% select(participant, fusion_variant, type, pred_cluster, fusion_cluster_att)


```



```{r}

tcga_data_matched_fusions %>% select(participant, fusion_variant, type, pred_cluster) %>%
  group_by(participant, fusion_variant, pred_cluster) %>%
  tally() %>%
  ggplot(aes(x=fusion_variant, y=n, fill=factor(pred_cluster))) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  

```


```{r}

tcga_data_matched_fusions %>% select(participant, fusion_variant, type, pred_cluster, fusion_cluster_att) %>%
  group_by(participant, fusion_variant, fusion_cluster_att) %>%
  tally() %>%
  ggplot(aes(x=fusion_variant, y=n, fill=fusion_cluster_att)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  

```




# Examine GTEx 

```{r}

gtex_data = data %>% filter(data_class == "GTEx")

gtex_data$participant = sapply(gtex_data$sample, function(x) { vals = str_split(x, "-")[[1]]; paste(vals[c(1,2)], collapse ="-") })

```

```{r}

gtex_samples_with_matched_fusions = gtex_data %>% group_by(participant, fusion_variant) %>% tally() %>% filter(n>1)

gtex_data_matched_fusions = left_join(gtex_samples_with_matched_fusions %>% select(participant, fusion_variant),
                                      gtex_data,
                                      by=c('participant', 'fusion_variant'))


```



```{r}


gtex_data_matched_fusions %>% select(participant, sample, fusion_variant, pred_cluster, fusion_cluster_att)

```


# Merge TCGA and GTEx matched fusion data

```{r}

data_matched_fusions = bind_rows(tcga_data_matched_fusions, gtex_data_matched_fusions)


```





```{r}

#  check reproducibility for cluster-level predictions

data_matched_fusions %>% group_by(participant, fusion_variant, pred_cluster) %>% 
  tally() %>% mutate(agree = (n>1)) %>%
  ggplot(aes(x=factor(pred_cluster), y=n, fill=agree)) + geom_col()


```


```{r}

#  check reproducibility for cluster-level predictions

data_matched_fusions %>% group_by(participant, fusion_variant, pred_cluster) %>% tally() %>% mutate(agree = (n>1)) %>%
  group_by(pred_cluster, agree) %>% summarize(sum_agree = sum(n)) %>%
   mutate(pct=prop.table(sum_agree))  %>%
  ggplot(aes(x=factor(pred_cluster), y=pct, fill=agree)) + geom_col()


```




```{r}

#  check reproducibility for cluster annotation-level predictions

data_matched_fusions %>% mutate(fusion_cluster_att = ifelse(grepl("artifact", fusion_cluster_att), "artifact", fusion_cluster_att) ) %>%
group_by(participant, fusion_variant, fusion_cluster_att) %>% tally() %>% mutate(agree = (n>1)) %>%
  ggplot(aes(x=fusion_cluster_att, y=n, fill=agree)) + geom_col()

```


```{r}

data_matched_fusions %>% mutate(fusion_cluster_att = ifelse(grepl("artifact", fusion_cluster_att), "artifact", fusion_cluster_att) ) %>%
group_by(participant, fusion_variant, fusion_cluster_att) %>% tally() %>% mutate(agree = (n>1)) %>%
  group_by(fusion_cluster_att, agree) %>% summarize(sum_agree = sum(n)) %>%
   mutate(pct=prop.table(sum_agree))  %>%
  ggplot(aes(x=fusion_cluster_att, y=pct, fill=agree)) + geom_col()


```







```{r}


library(igraph)

combined_results = full_join(data_matched_fusions %>% select(participant, sample, fusion_variant, pred_cluster, fusion_cluster_att),
                             data_matched_fusions %>% select(participant, sample, fusion_variant, pred_cluster, fusion_cluster_att),
                             by = c('participant', 'fusion_variant') ) %>%
  filter(sample.x != sample.y)



combined_results %>% group_by(pred_cluster.x, pred_cluster.y) %>% tally() 


```


```{r}

combined_results %>% 
  group_by(pred_cluster.x, pred_cluster.y) %>% 
  tally() %>% 
  ggplot(aes(x=factor(pred_cluster.x), y=n, fill=factor(pred_cluster.y))) + geom_col() +
  ggtitle("Cluster assignment for matched participant sample fusions")


```

```{r}

# examine matched sample fusions according to the high-level categories
combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>% tally() 



```


```{r}

combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>% tally() %>%
  ggplot(aes(x=fusion_cluster_att.x, y=n, fill=fusion_cluster_att.y)) + geom_col() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  ggtitle("High-level category assignment for matched participant diff sample fusions")


```


```{r}

# examine fractional representation of the above
combined_results %>% group_by(fusion_cluster_att.x, fusion_cluster_att.y) %>%  tally() %>%
  group_by(fusion_cluster_att.x) %>% mutate(pct=prop.table(n))  %>%
  ggplot(aes(x=fusion_cluster_att.x, y=pct, fill=fusion_cluster_att.y)) + geom_col() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("High-level category assignment for matched participant diff sample fusions")

```


```{r}


consistency_stats = combined_results %>% select(pred_cluster.x, pred_cluster.y) %>% group_by(pred_cluster.x, pred_cluster.y) %>% tally() %>%
  group_by(pred_cluster.x) %>% mutate(pct=prop.table(n)) %>% mutate(ident_cluster = (pred_cluster.x==pred_cluster.y))

consistency_stats %>% ggplot(aes(x=pred_cluster.x, y=pct, color=ident_cluster)) + geom_col() + 
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(1) )) + 
  ggtitle("Cluster assignment for participant matched diff sample fusion pairs")

```

```{r}



graph_weights = consistency_stats %>%  select(i=pred_cluster.x, j=pred_cluster.y, weight=pct)  %>% 
  filter(weight > 0.01) %>% unique()

prediction_accuracy_graph = graph_from_data_frame(graph_weights, directed=FALSE)


g.simplified = simplify(prediction_accuracy_graph)
g.louvain = cluster_louvain(prediction_accuracy_graph, resolution=1)

plot(g.louvain, 
     g.simplified, 
     vertex.size=3, edge.arrow.size = .2)


```


```{r}

load("../3.2.EvaluateClusterPredictionAccuracy/share_data.Rdata")

for (i in 1:length(g.louvain)) {
    clustered_ids = g.louvain[[i]]
    if (length(clustered_ids) > 1) {
        plot_heatmap_n_fusion_counts(clustered_ids)
    }
}

```


# Examine the artifact fusions


```{r}

artif_fusion_variants = data %>%  filter(grepl("artifa", fusion_cluster_att)) %>% select(fusion_variant, tissue_type) %>% 
  group_by(fusion_variant, tissue_type) %>% tally()


artif_fusion_variants 

```




```{r}

artif_fusion_variants = data %>%  filter(grepl("artifa", fusion_cluster_att)) %>% group_by(fusion_variant) %>% tally() %>% filter(n>1) 

artif_fusion_variants = left_join(artif_fusion_variants, data) 

artif_fusion_variants %>% group_by(fusion_cluster_att) %>% tally() %>% ggplot(aes(x=fusion_cluster_att, y=n, fill=fusion_cluster_att)) +
  geom_col()  + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

Artifact fusion variants are mostly consistent in their annotation as artifacts when found among any samples in which they occur. 
