---
title: "CompareAssignments"
author: "bhaas"
date: '2022-08-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}

targeted_data = read.table(gzfile("../../data/FusionInspector.v2.4.0.C4_targeted_fusions.tsv.gz"), header=T, sep="\t", stringsAsFactors = F)

targeted_data= targeted_data %>% mutate(fusion_variant = paste(sample_name, fusion_name, LeftBreakpoint, RightBreakpoint))




```

```{r}

init_data = read.table(gzfile("../../data/FusionInspector.v2.4.0.examine_recurrents.tsv.gz"), header=T, sep="\t", stringsAsFactors = F)

init_data= init_data %>% mutate(fusion_variant = paste(sample_name, fusion_name, LeftBreakpoint, RightBreakpoint))


```

```{r}

merged_data = inner_join(targeted_data, init_data, by='fusion_variant', suffix=c('.targeted', '.init'))

```


```{r}

merged_data %>% select(fusion_variant, JunctionReadCount.targeted, SpanningFragCount.targeted, fusion_cluster_att.targeted,
                       JunctionReadCount.init, SpanningFragCount.init, fusion_cluster_att.init)

```

```{r}

merged_data %>% group_by(fusion_cluster_att.init, fusion_cluster_att.targeted) %>% tally() 

```

```{r}

merged_data %>% group_by(fusion_cluster_att.init, fusion_cluster_att.targeted) %>% tally() %>%
  ggplot(aes(x=fusion_cluster_att.init, y=n, fill=fusion_cluster_att.targeted)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


```

```{r}


merged_data %>% group_by(fusion_cluster_att.init, fusion_cluster_att.targeted) %>% tally() %>%
  group_by(fusion_cluster_att.init) %>% mutate(pct=prop.table(n)) %>%
  ggplot(aes(x=fusion_cluster_att.init, y=pct, fill=fusion_cluster_att.targeted)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))



```






