---
title: "C4_targeted_FI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
```

```{r}

fusion_data = read.table(gzfile("../data/FusionInspector.v2.4.0.C4_targeted_fusions.tsv.gz"), header=T, 
                         sep="\t", stringsAsFactors = F)

FI_samples = read.table("../data/FusionInspector.v2.4.0.C4_targeted_fusions.sample_list", header=F, stringsAsFactors = F)[,1]

fusions_of_interest = fusion_data %>% select(fusion_name) %>% unique() %>% pull(fusion_name)

```


```{r}
# count GTEx samples
sum(grepl("GTEX", FI_samples))
# 1009

# count TCGA samples:
sum(! grepl("GTEX", FI_samples))
# 2764

```



Assess fusion cluster prediction types.

```{r}

fusion_annot_class_stats = fusion_data %>% filter(is_primary) %>%
    mutate(annot_type = fusion_cluster_att) %>%
    mutate(annot_type = ifelse((is.na(fusion_cluster_att) | fusion_cluster_att == "NA"), "other", fusion_cluster_att)) %>%
    mutate(annot_type = ifelse(grepl("artifact", fusion_cluster_att), "artifact", annot_type)) %>%
    mutate(annot_type = ifelse(pred_cluster %in% c(49,51), "high_counter_evidence", annot_type)) %>% 
    group_by(fusion_name, cosmic, annot_type) %>% tally() %>% mutate(frac=prop.table(n)) %>%
    select(-n) %>%
    spread(key=annot_type, value=frac, fill=0) 



fusion_annot_class_stats

write.table(fusion_annot_class_stats, file="fusion_annot_class_stats.tsv", quote=F, sep="\t", row.names = F)
```



```{r}
# stats for the cosmic subset:
fusion_annot_class_stats %>% filter(cosmic & `COSMIC-like` > 0) %>% arrange(`COSMIC-like`)
#25 / 31 

```






```{r}
# how many have cosmic-like predictions?
fusion_annot_class_stats%>% filter(`COSMIC-like` > 0) %>% nrow()
# 205  (and so, 236-305 = 31 do not)


```


```{r}
# how many counter-evidence >= 10%
fusion_annot_class_stats%>% filter( high_counter_evidence >= 0.1) %>% nrow()

# 7
```

```{r}
# how many with artifacts?
fusion_annot_class_stats%>% filter( artifact > 0)
# 9

```


```{r}
# pull in the original STAR-Fusion results for T/N findings and other annotated fusion attributes.

orig_STARF_fusion_preds = read.table(gzfile("../data/TCGA_n_GTEx.STAR-Fusion.v1.7.fusion_preds.decorated.tsv.gz"), 
                                     header=T, sep="\t", stringsAsFactors = F) %>%
    filter(fusion_name %in% fusions_of_interest)


orig_STARF_tumor_normal_stats = read.table(gzfile("../data/TCGA_n_GTEx.STAR-Fusion.v1.7.fusion_preds.stats.tsv.gz"), 
                                           header=T, sep="\t", stringsAsFactors = F) %>%
    filter(fusion_name %in% fusions_of_interest)


orig_STARF_tumor_normal_expression_stats = read.table(gzfile("../data/TCGA_n_GTEx.STAR-Fusion.v1.7.tumor_normal_fusion_expression_comparison_stats.tsv.gz"), 
                                                      header=T, sep="\t", stringsAsFactors = F) %>%
    filter(fusion_name %in% fusions_of_interest)

# merge expression stats into the tumor/normal stats
orig_STARF_tumor_normal_stats = left_join(orig_STARF_tumor_normal_stats, orig_STARF_tumor_normal_expression_stats, by='fusion_name')

# rank fusions by logTN

fusions_ranked_by_logTN = orig_STARF_tumor_normal_stats %>% arrange(desc(logTN)) %>% pull(fusion_name)

fusion_data$fusion_name = factor(fusion_data$fusion_name, levels=fusions_ranked_by_logTN)

orig_STARF_fusion_preds$fusion_name = factor(orig_STARF_fusion_preds$fusion_name, levels=fusions_ranked_by_logTN)

orig_STARF_tumor_normal_stats$fusion_name = factor(orig_STARF_tumor_normal_stats$fusion_name, levels=fusions_ranked_by_logTN)

fusion_annot_class_stats$fusion_name = factor(fusion_annot_class_stats$fusion_name, levels=fusions_ranked_by_logTN)


write.table(orig_STARF_tumor_normal_stats, "fusions_236_logTN_stats.tsv", quote=F, sep="\t", row.names = F)
```




```{r}

fusion_annot_class_stats_gathered = fusion_annot_class_stats %>%
    gather(key=cluster_annot_type, value=frac_fusions, `COSMIC-like`, artifact, other)
```


```{r}
fusion_annot_class_stats_gathered %>%
    ggplot(aes(x=fusion_name, y=frac_fusions)) + geom_col(aes(fill=cosmic)) +
    facet_wrap(~cluster_annot_type, ncol = 1) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(0.3) ))
```

For Figure 6 (but see make_Figures.Rmd for adjustments)

```{r}

source("../Rlib/fusion_plotting_routines.R")

plot_ranked_fusions(fusions_ranked_by_logTN)

```

For Figure S5 (but see make_Figures.Rmd for adjustments)


```{r}

batch_ranked_fusion_plots(fusions_ranked_by_logTN)

```


# querying aspects of the data

```{r}

# How many of these fusions are found at substantial levels in normal tissues?

orig_STARF_tumor_normal_stats %>% arrange(desc(logTN)) %>% filter(abs(normal) >= 5) %>% nrow()

# 86

```



```{r}


fusion_list = fusions_ranked_by_logTN


tcga_type_fractions = orig_STARF_fusion_preds %>% filter(fusion_name %in% fusion_list) %>%
        filter(data_class == "TCGA" & tumor_or_normal == "tumor") %>%
        filter(is_primary) %>%
        group_by(fusion_name, tissue_type) %>%
        tally(name='tissue_count') %>%
        group_by(fusion_name) %>%
        mutate(tissue_fraction = tissue_count / sum(tissue_count)) %>% select(-tissue_count)


head(tcga_type_fractions)

fusion_to_tcga_tumor_type_count = tcga_type_fractions %>% group_by(fusion_name) %>% tally(name='tcga_tumor_type_count')

head(fusion_to_tcga_tumor_type_count)



# FGFR3::TACC3	11			
# CCAT1::CASC8	9			
# VCL::ADK	12			
# TMPRSS2::ERG	2			
# RP11-400N13.3::RP11-815M8.1	29			
# CCDC6::RET	3

```


```{r}

gtex_type_fractions = orig_STARF_fusion_preds %>% filter(fusion_name %in% fusion_list) %>%
        filter(data_class == "GTEx") %>%
        filter(is_primary) %>%
        group_by(fusion_name, tissue_type) %>%
        tally(name='tissue_count') %>%
        group_by(fusion_name) %>%
        mutate(tissue_fraction = tissue_count / sum(tissue_count)) %>%
        select(-tissue_count)

head(gtex_type_fractions)

fusion_to_gtex_normal_type_count = gtex_type_fractions %>% group_by(fusion_name) %>% tally(name='gtex_normal_type_count')
head(fusion_to_gtex_normal_type_count)

# TMPRSS2::ERG	1			
# RP11-400N13.3::RP11-815M8.1	10			
# RP11-206M11.7::TM4SF1-AS1	1			
# RP11-109J4.1::ATP10B	3			
# AC005534.8::LINC01006	1			
# AC005618.6::PCDHGB7	1	

```

```{r}

fusion_to_tcga_gtex_tissue_type_counts = full_join(fusion_to_tcga_tumor_type_count, fusion_to_gtex_normal_type_count, by='fusion_name')

fusion_annot_class_stats_ext1 = full_join(fusion_annot_class_stats, fusion_to_tcga_gtex_tissue_type_counts, by='fusion_name')

fusion_annot_class_stats_ext2 = full_join(fusion_annot_class_stats_ext1,
                                          orig_STARF_fusion_preds %>% select(fusion_name, structure_type) %>% 
                                          unique() %>% 
                                          filter(fusion_name %in%  fusion_annot_class_stats_ext1$fusion_name),
                                        by='fusion_name')

fusion_annot_class_stats_ext3 = full_join(fusion_annot_class_stats_ext2, 
                                          orig_STARF_tumor_normal_stats %>% select(fusion_name, normal, tumor, total, logTN),
                                          by='fusion_name')
```


```{r}

fusions_in_mult_normals_n_tissues = fusion_annot_class_stats_ext3 %>% filter(normal >= 5  & gtex_normal_type_count >= 5)

fusions_in_mult_normals_n_tissues 

fusions_in_mult_normals_n_tissues  %>% group_by(structure_type) %>% tally()


# INTERCHR	1			
# IntraCHR	20+14 = 34			
# READTHRU	26	

```

```{r}

fusions_in_mult_normals_n_tissues  %>% group_by(structure_type) %>% tally() %>% summarize(sum(n))

# 61

```





```{r}

save.image("fusion_data_for_main_figs.Rdata")

```



# misc stats

```{r}

orig_STARF_tumor_normal_stats %>% filter(fusion_name == "FGFR3::TACC3")

```

```{r}

orig_STARF_tumor_normal_stats %>% filter(fusion_name == "CCAT1::CASC8")

orig_STARF_fusion_preds %>% filter(fusion_name == "CCAT1::CASC8") %>% select(sample) %>% unique() %>% arrange(sample)


```



