---
title: "FI_new_fusions_class_predictions"
author: "Brian Haas"
date: "7/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

For each of the 236 fusions targeted, see how many new examples we have for each given the target samples explored


```{r}


initial_FI_fusion_data = read.table(gzfile("../data/FusionInspector.v2.4.0.examine_recurrents.tsv.gz"), header=T, sep="\t", stringsAsFactors = F)

screening_236_fusions = read.table("FI_screened_236_fusions.tsv", header=F, stringsAsFactors = F)[,1]

initial_FI_fusion_data = initial_FI_fusion_data %>% filter(fusion_name %in% screening_236_fusions)

initial_FI_fusion_data = initial_FI_fusion_data %>% 
  mutate(fusion_occurrence = paste(sample, fusion_name) )%>%
  mutate(fusion_occurrence_isoform = paste(sample, fusion_name, LeftBreakpoint, RightBreakpoint))


screened_FI_fusion_data = read.table("../data/FusionInspector.v2.4.0.C4_targeted_fusions.tsv.gz", header=T, sep="\t", stringsAsFactors = F)

screened_FI_fusion_data = screened_FI_fusion_data %>% 
  mutate(fusion_occurrence = paste(sample, fusion_name)) %>%
  mutate(fusion_occurrence_isoform = paste(sample, fusion_name, LeftBreakpoint, RightBreakpoint))


```


Identify the newly screened fusions

```{r}

initial_FI_fusion_occurrences = initial_FI_fusion_data %>% select(fusion_occurrence, sample, fusion_name, data_class) %>% unique()
new_FI_fusion_occurrences = screened_FI_fusion_data %>% select(fusion_occurrence, sample, fusion_name, data_class) %>% unique()

initial_FI_fusion_occurrences$initial = TRUE
new_FI_fusion_occurrences$screened = TRUE

merged = full_join(initial_FI_fusion_occurrences, new_FI_fusion_occurrences, by=c('fusion_occurrence', 'sample', 'fusion_name', 'data_class' ),)

merged[is.na(merged)] = FALSE

```

```{r}

merged %>% select(initial, screened) %>% group_by(initial, screened) %>% tally()

merged[is.na(merged)] = FALSE

```


```{r}

# just the new ones

merged %>% filter(screened & ! initial) %>% group_by(fusion_name) %>% tally() %>% arrange(desc(n))

```


```{r}

screened_fusion_counts = merged %>% filter(screened) %>% group_by(fusion_name) %>% tally() 

screened_fusion_counts %>% ggplot(aes(x=reorder(fusion_name, -n), y=n+1)) + geom_col() +  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=rel(0.5))) + scale_y_log10() 

```



```{r}

screened_fusions_rankings = screened_fusion_counts %>% arrange(desc(n)) %>% pull(fusion_name)

merged$fusion_name = factor(merged$fusion_name, levels=screened_fusions_rankings)

# include the confirmed and new ones (leaving out just the initial not pursued or confirmed later)


merged %>% filter(screened)  %>% group_by(fusion_name) %>% tally() %>% arrange(desc(n))

```

```{r}

merged %>% filter(screened) %>% group_by(fusion_name, initial) %>% tally()  %>% ggplot(aes(x=fusion_name, y=n+1, fill=initial)) + geom_col() +  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=rel(0.5))) 
#+ scale_y_log10() 

```




```{r}
merged %>% filter(screened) %>% group_by(fusion_name, initial) %>% tally() %>%  group_by(fusion_name) %>% mutate(fraction=prop.table(n)) %>% ggplot(aes(x=fusion_name, y=fraction, fill=initial)) + geom_col() +  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=rel(0.5))) 
```


